In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits =load_digits()

In [ ]:
#import kfold library from sklearn
from sklearn.model_selection import KFold
#creating an object and spliting it into 3 folds
obj = KFold(n_splits=3)
obj


KFold(n_splits=3, random_state=None, shuffle=False)

In [ ]:
for train_index, test_index in obj.split([1,2,3,4,5,6,7,8]):
  print(train_index, test_index)


[3 4 5 6 7] [0 1 2]
[0 1 2 6 7] [3 4 5]
[0 1 2 3 4 5] [6 7]


In [ ]:
def cal_score(model, X_train, X_test, Y_train, Y_test):
  model.fit(X_train, Y_train)
  return model.score(X_test, Y_test)


In [ ]:
# startifiedKFold is better because it divides the fold into uniform fold
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_lr =[]
scores_svm = []
scores_dt = []

for train_index, test_index in folds.split(digits.data,digits.target):
  X_train , X_test,  Y_train , Y_test = digits.data[train_index],digits.data[test_index],\
                                        digits.target[train_index],digits.target[test_index]
  scores_lr.append(cal_score(LogisticRegression(),X_train,X_test,Y_train,Y_test))
  scores_svm.append(cal_score(SVC(),X_train,X_test,Y_train,Y_test))
  scores_dt.append(cal_score(RandomForestClassifier(n_estimators=30),X_train,X_test,Y_train,Y_test))




/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


In [ ]:
scores_lr

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [ ]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [ ]:
scores_dt

[0.9248747913188647, 0.9382303839732888, 0.9115191986644408]